### ISSUE TITLE
/metabbs/ 나 /metabbs/board/의 디폴트 액션

### ISSUE THREAD

**Issue by dittos** [MetaBBS/metabbs#9]
현재는 아무런 디폴트 액션이 없습니다.

단순히 php 에러를 내는 것 보다는 MetaBBS의 주소를 알려주는 안내와 같은 "공익 액션"이 나을 것 같습니다.

**Comment by dittos** [comment]
Milestone 0.9a3 deleted

--ditto

**Comment by devilzz** [comment]
좋은 아이디어입니다. 친절한 메타비비에스 였으면 합니다.
